import type { FieldType, PartialDottedKeys } from "./types";
export declare const ZERO_ADDRESS: "0x0000000000000000000000000000000000000000";
export declare const isNotNull: <T>(v: T | null) => v is T;
export declare const isNotUndefined: <T>(v: T | undefined) => v is T;
export declare const isDefined: <T>(v?: T | null) => v is T;
export declare const bigIntComparator: <T>(getter: (x: T) => bigint | undefined | null, order?: "asc" | "desc") => (a: T, b: T) => 1 | 0 | -1;
export declare const hasValue: <T, Path extends PartialDottedKeys<T> = PartialDottedKeys<T>>(data: T, path: Path) => data is T & { [path in Path]: NonNullable<FieldType<T, path>>; };
export declare const createHasValue: <T, Path extends PartialDottedKeys<T> = PartialDottedKeys<T>>(path: Path) => (data: T) => data is T & { [path in Path]: NonNullable<FieldType<T, path>>; };
export declare const getValue: <T, Path extends PartialDottedKeys<T> = PartialDottedKeys<T>>(data: T, path: Path) => FieldType<T, Path>;
export declare const transformValue: <T, R>(value: T | null | undefined, _transform: (v: T) => R) => R | null | undefined;
export declare const createGetValue: <T, Path extends PartialDottedKeys<T> = PartialDottedKeys<T>>(path: Path) => (data: T) => FieldType<T, Path>;
export declare const keys: <T>(o?: T) => (T extends ArrayLike<unknown> ? `${number}` : `${Extract<keyof T, number>}` | Extract<keyof T, string>)[];
export declare const values: <T>(o?: T) => (T extends ArrayLike<infer U> ? U : T[keyof T])[];
export declare const entries: <T>(o?: T) => [keyof T, T extends ArrayLike<infer U> ? U : T[keyof T]][];
export declare const fromEntries: <K extends PropertyKey, T>(srcEntries: Iterable<readonly [K, T]>) => Record<K, T>;
export declare const mergeEntries: <K extends PropertyKey, T>(srcEntries: Iterable<readonly [K, T]>, merger: (prev: T, value: T) => T) => Record<K, T>;
export declare const retryPromiseLinearBackoff: <R>(func: () => R, { timeout, retries, onError, }: {
    timeout?: number;
    retries?: number;
    onError?: (error: unknown, index: number) => unknown | Promise<unknown>;
}) => Promise<R>;
export declare function getLast<T>(array: [T, ...(T | null | undefined)[]]): T;
export declare function getLast<T>(array: T[]): T | undefined;
export declare function filterDefined<T>(array: [T, ...(T | null | undefined)[]]): [T, ...T[]];
export declare function filterDefined<T>(array: (T | null | undefined)[]): T[];
export declare function getLastDefined<T>(array: [T, ...(T | null | undefined)[]]): T;
export declare function getLastDefined<T>(array: (T | null | undefined)[]): T | undefined;
export declare function deepFreeze<T>(obj: T): T;
